import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Alegreya } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import MainLayout from "@/components/layout/main-layout";
import { ThemeProvider } from "@/components/providers/theme-provider";

const alegreya = Alegreya({ subsets: ["latin"], variable: "--alegreya" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(GeistSans.className, alegreya.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <MainLayout>{children}</MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
